<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DotML\DotML.csproj" />
    <ProjectReference Include="..\..\DotML.Utils\ImageResize\ImageResize.csproj" />
    <ProjectReference Include="..\..\DotML.Utils\Images2ImagesDataset\Images2ImagesDataset.csproj" />
  </ItemGroup>

</Project>
